[package]
name = "twintail"
version = "1.2.0"
edition = "2024"

[workspace]
members = [".", "crates/*"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[profile.dev]
opt-level = 1
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 256
panic = 'unwind'

[workspace.dependencies]
twintail_cli = { path = "crates/twintail_cli" }
twintail_common = { path = "crates/twintail_common" }
twintail_core = { path = "crates/twintail_core" }
twintail_sekai = { path = "crates/twintail_sekai" }

aes = "0.8.4"
anstyle = "1.0.10"
cbc = { version = "0.1.2", features = ["alloc"] }
clap = { version = "4.5.20", features = ["derive"] }
fs2 = "0.4.3"
futures = "0.3.31"
hmac = "0.12.1"
humansize = "2.1.3"
indicatif = { version = "0.17.8" }
jwt = "0.16.0"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = "0.12.9"
rmp-serde = "1.3.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_plain = "1.0.2"
sha2 = "0.10.8"
thiserror = "1.0.66"
tokio = { version = "1.41.0", features = ["full"] }
tokio-retry = "0.3.0"
zip = "2.2.1"
mockito = "1.5.0"
tempfile = "3.13.0"

[dependencies]
twintail_cli.workspace = true
twintail_common.workspace = true
twintail_core.workspace = true
twintail_sekai.workspace = true
tokio.workspace = true

